
# GitHub Action to run flakehell through reviewdog.
# flakehell (https://github.com/flakehell) integrates well with legacy code
# reviewdog (https://github.com/reviewdog) adds inline comments for PRs/commits
#
# This Action was created using reviewdog's Action Template
# https://github.com/reviewdog/action-template
name: 'Run flakehell with reviewdog'
description: '🐶 Run flakehell with reviewdog on pull requests to improve code review experience.'
author: 'Balint Gyimesi'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: false
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
    required: false

  ### Flags for reviewdog
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
    required: false
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
    required: false
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
    required: false
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    required: false
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false

  ### Flags for flakehell
  # None currently, flakehell is configured through pyproject.toml

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check-circle'
  color: 'blue'
