[tool.flakehell]
# Needed due to https://github.com/flakehell/flakehell/issues/10
extended_default_ignore=[]
max_line_length = 88
# show line of source code in output
show_source = true
# baseline = ".flakehell.baseline"
