name: Test Flakehell with Reviewdog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-PythonFlakehell:
    name: runner / flakehell (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / flakehell (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          locale: "US"
          workdir: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / flakehell (github-pr-review with locale and error)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          reviewdog_flags: "-filter-mode=file -fail-on-error"
